"""initial schema

Revision ID: 126e20ba0e26
Revises: 
Create Date: 2026-05-01 08:15:58.168301

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '126e20ba0e26'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('notebooks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.Enum('PUBLIC', 'TEAM', name='visibility', native_enum=False, length=16), nullable=False),
    sa.Column('allowed_groups', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'slug', name='uq_notebook_owner_slug')
    )
    with op.batch_alter_table('notebooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notebooks_slug'), ['slug'], unique=False)

    op.create_table('notebook_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notebook_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('published_by', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notebook_id', 'version', name='uq_notebook_version')
    )
    with op.batch_alter_table('notebook_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notebook_versions_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_notebook_versions_notebook_id'), ['notebook_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notebook_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notebook_versions_notebook_id'))
        batch_op.drop_index(batch_op.f('ix_notebook_versions_content_hash'))

    op.drop_table('notebook_versions')
    with op.batch_alter_table('notebooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notebooks_slug'))

    op.drop_table('notebooks')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    # ### end Alembic commands ###
